name: tiktok_login_flutter_example
description: Demonstrates how to use the tiktok_login_flutter plugin.

publish_to: "none"

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  tiktok_login_flutter:
    path: ../

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
