name: tiktok_login_flutter
description: Fork of TikTok login for flutter.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.raiinmaker.tiktok_login_flutter
        pluginClass: TiktokLoginFlutterPlugin
      ios:
        pluginClass: TiktokLoginFlutterPlugin
      web:
        pluginClass: TiktokLoginFlutterWeb
        fileName: tiktok_login_flutter_web.dart
